# Generated by Django 4.2.1 on 2024-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyamentStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_id', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
    ]
